
package com.revature.soap_server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://soap_server.revature.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://soap_server.revature.com/", className = "com.revature.soap_server.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://soap_server.revature.com/", className = "com.revature.soap_server.SayHiResponse")
    public String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "work", targetNamespace = "http://soap_server.revature.com/", className = "com.revature.soap_server.Work")
    @ResponseWrapper(localName = "workResponse", targetNamespace = "http://soap_server.revature.com/", className = "com.revature.soap_server.WorkResponse")
    public void work(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
